/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/bitcoin.glb -o src/components/Bitcoin.jsx -r public -k 
*/

import React, { useEffect, useRef } from 'react'
import { useEnvironment, useGLTF, useScroll } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';
import * as THREE from 'three';
import gsap from 'gsap';

const  OrbitCoin =({triggerExplosion,trigger,active,...props}) =>{
  const { nodes, materials } = useGLTF('./models/bitcoin.glb')
  const group= useRef();
  const env = useEnvironment({files :'./textures/gold.jpg'})
  const scroll= useScroll();
  const tl = useRef();
  useEffect(()=>{
    group.current.material.envMap = env;
    group.current.material.transparent=true;
   
  })
  useEffect(() => {
    if (!tl.current) return;

  if (active) {
    tl.current.pause();     // ⏸ stop orbit + spin
  } else {
    tl.current.resume();    // ▶ continue orbit + spin
  }
  const coin = group.current;
  if (!coin || !coin.material) return;

  // Ensure transparency is enabled
  coin.material.transparent = true;
 
  if (triggerExplosion || trigger) {
   
    // Fade OUT
    gsap.to(coin.material, {
      opacity: 0,
      duration: 0.6,
      onComplete: () => {
        coin.visible = false;
      }
    });
  } else {
    // Make it visible first
    coin.visible = true;

    // Fade IN
    gsap.to(coin.material, {
      opacity: 1,
      duration: 0.6,
    });
  }
}, [triggerExplosion,active,trigger]);

let radius = 4.5
let responsiveScale = 2;
  if(window.innerWidth<769){
    radius = 3.5;
  }
  else if(window.innerWidth<480){
    radius=2.3;
    responsiveScale=1.5;
  }  else {radius= 4.5;
    responsiveScale= 2;
  }
    const speed = 0.5 // orbit speed
    let angle = 0;

  
   useEffect(() => {
    const coin = group.current;
    if (!coin) return;

    coin.material.transparent = true;

    // RESET timeline
    if (tl.current) tl.current.kill();
    tl.current = gsap.timeline({ repeat: -1 });

    // INTERNAL ANIMATION VALUES
    const state = { angle: 0 };

    // Orbit + spin animation (runs forever)
    tl.current.to(state, {
      angle: Math.PI * 2,
      duration: 8,
      ease: "none",
      onUpdate: () => {
        // Orbit
        coin.position.x = radius * Math.sin(state.angle);
        coin.position.z = radius * Math.cos(state.angle);
        coin.position.y = 0.8 * Math.sin(state.angle * 2);

        // Spin
        coin.rotation.y -= 0.03;
        coin.rotation.x -= 0.02;
         coin.rotation.z -= Math.sin(0.03);
      }
    });
  }, []);
  
  return (
    <group {...props} dispose={null} scale={responsiveScale}>
      <mesh name="Cylinder001"  ref={group} geometry={nodes.Cylinder001.geometry} material={materials['Gold.004']} rotation={[Math.PI*1.5, 0, Math.PI]} scale={[0.388, 0.039, 0.388]} />
    </group>
  )
}

useGLTF.preload('./models/bitcoin.glb')
export default OrbitCoin;