/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/three-coin.glb -o src/components/ThreeCoin.jsx -r public -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/three-coin.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="Coin_Coin_0001" geometry={nodes.Coin_Coin_0001.geometry} material={materials['Gold.001']} position={[0.855, -1.154, -0.448]} rotation={[-2.765, -0.188, -2.891]} scale={0.467} />
      <mesh name="Coin_Coin_0002" geometry={nodes.Coin_Coin_0002.geometry} material={materials['Gold.001']} position={[0.311, -1.642, -0.359]} rotation={[-0.316, -0.239, -0.058]} scale={0.414} />
      <mesh name="Coin_Coin_0003" geometry={nodes.Coin_Coin_0003.geometry} material={materials['Gold.001']} position={[1.896, -2.098, -0.399]} rotation={[-1.793, 0.878, -1.496]} scale={0.467} />
      <mesh name="Coin_Coin_0004" geometry={nodes.Coin_Coin_0004.geometry} material={materials['Gold.001']} position={[-1.075, -0.992, -0.171]} rotation={[-3.019, -1.498, -2.907]} scale={0.414} />
      <mesh name="Coin_Coin_0005" geometry={nodes.Coin_Coin_0005.geometry} material={materials['Gold.001']} position={[-1.196, -1.48, -0.441]} rotation={[3.005, 0.121, -0.033]} scale={0.467} />
      <mesh name="pa002" geometry={nodes.pa002.geometry} material={materials['Gold.001']} position={[1.765, -1.092, 0.179]} rotation={[-2.91, -0.114, -0.17]} scale={0.414} />
      <mesh name="Coin_Coin_0006" geometry={nodes.Coin_Coin_0006.geometry} material={materials['Gold.001']} position={[-0.451, -1.043, -0.848]} rotation={[-2.893, 0.547, -0.231]} scale={0.467} />
      <mesh name="Coin_Coin_0007" geometry={nodes.Coin_Coin_0007.geometry} material={materials['Gold.001']} position={[-0.739, -1.869, -0.528]} rotation={[0.041, -0.801, -0.354]} scale={0.414} />
      <mesh name="Coin_Coin_0008" geometry={nodes.Coin_Coin_0008.geometry} material={materials['Gold.001']} position={[-0.409, -0.918, -1.008]} rotation={[-2.925, 0.421, -0.216]} scale={0.467} />
      <mesh name="Coin_Coin_0011" geometry={nodes.Coin_Coin_0011.geometry} material={materials['Gold.001']} position={[0.526, -1.081, 0.679]} rotation={[2.909, -0.193, 0.702]} scale={0.467} />
      <mesh name="Coin_Coin_0015" geometry={nodes.Coin_Coin_0015.geometry} material={materials['Gold.001']} position={[-0.471, -1.475, 1.534]} rotation={[-1.148, -0.112, -0.101]} scale={0.414} />
      <mesh name="Coin_Coin_0016" geometry={nodes.Coin_Coin_0016.geometry} material={materials['Gold.001']} position={[0.261, -1.528, 0.69]} rotation={[2.877, -0.326, 0.239]} scale={0.414} />
      <mesh name="pa003" geometry={nodes.pa003.geometry} material={materials['Gold.001']} position={[2.108, -1.374, 0.685]} rotation={[-0.957, 1.051, 0.604]} scale={0.414} />
      <mesh name="Coin_Coin_0019" geometry={nodes.Coin_Coin_0019.geometry} material={materials['Gold.001']} position={[-0.606, -1.059, 1.136]} rotation={[-1.358, -0.792, 2.008]} scale={0.414} />
      <mesh name="Coin_Coin_0024" geometry={nodes.Coin_Coin_0024.geometry} material={materials['Gold.001']} position={[0.126, -1.392, 0.474]} rotation={[3.101, -0.558, 0.513]} scale={0.414} />
      <mesh name="Coin_Coin_0029" geometry={nodes.Coin_Coin_0029.geometry} material={materials['Gold.001']} position={[-1.164, -1.232, 0.902]} rotation={[-3.1, -0.353, -0.125]} scale={0.414} />
      <mesh name="Coin_Coin_0030" geometry={nodes.Coin_Coin_0030.geometry} material={materials['Gold.001']} position={[0.813, -2.466, 0.27]} rotation={[2.933, -0.468, 0.144]} scale={0.414} />
      <mesh name="Cylinder015" geometry={nodes.Cylinder015.geometry} material={materials['Gold.001']} position={[-1.166, -1.411, 0.883]} scale={[0.388, 0.039, 0.388]} />
      <mesh name="Cylinder016" geometry={nodes.Cylinder016.geometry} material={materials['Gold.001']} position={[1.105, -1.582, 0.883]} scale={[0.388, 0.039, 0.388]} />
      <mesh name="Cylinder017" geometry={nodes.Cylinder017.geometry} material={materials['Gold.001']} position={[-0.02, -2.275, 0.883]} rotation={[0, 0, -0.493]} scale={[0.388, 0.039, 0.388]} />
      <mesh name="Cylinder018" geometry={nodes.Cylinder018.geometry} material={materials['Gold.001']} position={[1.1, -0.868, 0.883]} rotation={[-0.046, 0.1, -0.154]} scale={[0.388, 0.039, 0.388]} />
      <mesh name="Cylinder019" geometry={nodes.Cylinder019.geometry} material={materials['Gold.001']} position={[-0.426, -0.628, 0.883]} rotation={[-0.046, 0.1, -0.154]} scale={[0.388, 0.039, 0.388]} />
      <mesh name="Cylinder020" geometry={nodes.Cylinder020.geometry} material={materials['Gold.001']} position={[-1.555, -0.949, 0.883]} rotation={[-0.046, 0.1, -0.154]} scale={[0.388, 0.039, 0.388]} />
      <mesh name="Cylinder021" geometry={nodes.Cylinder021.geometry} material={materials['Gold.001']} position={[-1.363, -0.731, 0.883]} rotation={[-0.046, 0.1, -0.154]} scale={[0.388, 0.039, 0.388]} />
      <mesh name="Cylinder022" geometry={nodes.Cylinder022.geometry} material={materials['Gold.001']} position={[-1.343, -0.567, 0.876]} rotation={[-0.025, -0.097, -0.02]} scale={[0.365, 0.025, 0.365]} />
      <mesh name="Cylinder023" geometry={nodes.Cylinder023.geometry} material={materials['Gold.001']} position={[0.335, -0.621, 0.876]} rotation={[-0.025, -0.097, -0.02]} scale={[0.365, 0.025, 0.365]} />
      <mesh name="Cylinder024" geometry={nodes.Cylinder024.geometry} material={materials['Gold.001']} position={[1.107, -0.698, 0.876]} rotation={[-0.025, -0.097, -0.02]} scale={[0.365, 0.025, 0.365]} />
      <mesh name="Cylinder025" geometry={nodes.Cylinder025.geometry} material={materials['Gold.001']} position={[1.003, -1.045, 0.274]} rotation={[-0.025, -0.097, -0.02]} scale={[0.365, 0.025, 0.365]} />
      <mesh name="Cylinder026" geometry={nodes.Cylinder026.geometry} material={materials['Gold.001']} position={[0.32, -0.813, -0.404]} rotation={[-0.025, -0.097, -0.02]} scale={[0.365, 0.025, 0.365]} />
      <mesh name="Cylinder027" geometry={nodes.Cylinder027.geometry} material={materials['Gold.001']} position={[-0.398, -0.683, -0.208]} rotation={[-0.025, -0.097, -0.02]} scale={[0.365, 0.025, 0.365]} />
      <mesh name="Cylinder028" geometry={nodes.Cylinder028.geometry} material={materials['Gold.001']} position={[0.938, -2.03, -0.273]} rotation={[-0.025, -0.097, -0.02]} scale={[0.351, 0.025, 0.365]} />
      <mesh name="Text005" geometry={nodes.Text005.geometry} material={materials['Gold.001']} position={[0.817, -2.001, -0.778]} scale={0.429} />
      <mesh name="Text006" geometry={nodes.Text006.geometry} material={materials['Gold.001']} position={[1.354, -1.801, -0.778]} scale={0.429} />
      <mesh name="Text007" geometry={nodes.Text007.geometry} material={materials['Gold.001']} position={[0.177, -1.958, -0.778]} rotation={[0, 0, -0.577]} scale={0.429} />
      <mesh name="Text008" geometry={nodes.Text008.geometry} material={materials['Gold.001']} position={[1.727, -1.611, -0.778]} rotation={[0, 0, -0.577]} scale={0.429} />
      <mesh name="Text009" geometry={nodes.Text009.geometry} material={materials['Gold.001']} position={[1.727, -1.611, -0.216]} rotation={[0, 0, -0.577]} scale={0.429} />
      <mesh name="Curve003" geometry={nodes.Curve003.geometry} material={materials['Gold.001']} position={[0.819, -1.98, 0.805]} rotation={[0.006, 0, 0]} scale={1.566} />
      <mesh name="Curve007" geometry={nodes.Curve007.geometry} material={materials['Gold.001']} position={[0.316, -1.736, 0.693]} rotation={[0.006, 0, 0]} scale={1.566} />
      <mesh name="Curve008" geometry={nodes.Curve008.geometry} material={materials['Gold.001']} position={[0.316, -1.966, 1.403]} rotation={[0.719, 0, 0]} scale={1.566} />
      <mesh name="Curve009" geometry={nodes.Curve009.geometry} material={materials['Gold.001']} position={[0.316, -2.025, 1.333]} rotation={[0.719, 0, 0]} scale={1.566} />
      <mesh name="Curve010" geometry={nodes.Curve010.geometry} material={materials['Gold.001']} position={[0.316, -2.19, 0.247]} rotation={[2.297, 0, 0]} scale={1.566} />
      <mesh name="Curve011" geometry={nodes.Curve011.geometry} material={materials['Gold.001']} position={[0.316, -1.374, -0.964]} rotation={[3.111, 0, 0]} scale={1.566} />
    </group>
  )
}

useGLTF.preload('/models/three-coin.glb')
